development:
  adapter: postgresql
  encoding: unicode
  database: barbot-rails_development
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

test:
  adapter: postgresql
  encoding: unicode
  database: barbot-rails_test
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>

production:
  adapter: postgresql
  encoding: unicode
  database: barbot-rails_production
  host: localhost
  port: <%= ENV["BOXEN_POSTGRESQL_PORT"] || 5432 %>